import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";
import Providers from "./providers";
import ProfileBar from "@/components/ProfileBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Providers>
          <main className="flex-1 flex flex-col w-full">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
